/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './test.service.module';
import * as i2 from './test/test.service';
export const TestServiceModuleNgFactory:i0.NgModuleFactory<i1.TestServiceModule> = i0.ɵcmf(i1.TestServiceModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,([] as any[])],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(4608,
          i2.TestService,i2.TestService,([] as any[])),i0.ɵmpd(512,i1.TestServiceModule,
          i1.TestServiceModule,([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2Jhc3RpZW4vRG9jdW1lbnRzL2Rldi9MYWJzL1Rlc3RQYWNrYWdlL3NyYy9hcHAvdGVzdC5zZXJ2aWNlLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy9iYXN0aWVuL0RvY3VtZW50cy9kZXYvTGFicy9UZXN0UGFja2FnZS9zcmMvYXBwL3Rlc3Quc2VydmljZS5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
