/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './test.component';
const styles_TestComponent:any[] = ([] as any[]);
export const RenderType_TestComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_TestComponent,data:{}});
export function View_TestComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted((null as any),['\n    '])),(_l()(),i0.ɵeld(0,(null as any),
      (null as any),1,'p',([] as any[]),(null as any),(null as any),(null as any),
      (null as any),(null as any))),(_l()(),i0.ɵted((null as any),['\n      test Works!\n    '])),
      (_l()(),i0.ɵted((null as any),['\n    ','\n  ']))],(null as any),(_ck,_v) => {
    var _co:i1.TestComponent = _v.component;
    const currVal_0:any = _co.yo;
    _ck(_v,3,0,currVal_0);
  });
}
export function View_TestComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'bm-test',([] as any[]),
      (null as any),(null as any),(null as any),View_TestComponent_0,RenderType_TestComponent)),
      i0.ɵdid(114688,(null as any),0,i1.TestComponent,([] as any[]),(null as any),
          (null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const TestComponentNgFactory:i0.ComponentFactory<i1.TestComponent> = i0.ɵccf('bm-test',
    i1.TestComponent,View_TestComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2Jhc3RpZW4vRG9jdW1lbnRzL2Rldi9MYWJzL1Rlc3RQYWNrYWdlL3NyYy9hcHAvdGVzdC90ZXN0LmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy9iYXN0aWVuL0RvY3VtZW50cy9kZXYvTGFicy9UZXN0UGFja2FnZS9zcmMvYXBwL3Rlc3QvdGVzdC5jb21wb25lbnQudHMiLCJuZzovLy9Vc2Vycy9iYXN0aWVuL0RvY3VtZW50cy9kZXYvTGFicy9UZXN0UGFja2FnZS9zcmMvYXBwL3Rlc3QvdGVzdC5jb21wb25lbnQudHMuVGVzdENvbXBvbmVudC5odG1sIiwibmc6Ly8vVXNlcnMvYmFzdGllbi9Eb2N1bWVudHMvZGV2L0xhYnMvVGVzdFBhY2thZ2Uvc3JjL2FwcC90ZXN0L3Rlc3QuY29tcG9uZW50LnRzLlRlc3RDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCJcbiAgICA8cD5cbiAgICAgIHRlc3QgV29ya3MhXG4gICAgPC9wPlxuICAgIHt7eW99fVxuICAiLCI8Ym0tdGVzdD48L2JtLXRlc3Q+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7b0JDQUEsMkNBQ0k7TUFBQTtNQUFBLDhCQUFHO01BRUM7O0lBQUE7SUFBQTs7OztvQkNIUjtNQUFBO2FBQUE7VUFBQTtJQUFBOzs7OyJ9
